#!/bin/sh
# time v0.1

logo="
\033[32m
\033[32m___________.__                
\033[32m\__    ___/|__| _____   ____  
\033[32m  |    |   |  |/     \_/ __ \ 
\033[32m  |    |   |  |  Y Y  \  ___/
\033[32m  |____|   |__|__|_|  /\___  >
\033[32m                    \/     \/ 
\033[0m
"
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/bin ]; then
  bin="/usr/bin"
elif [ -d /bin ]; then
  bin="/bin"
fi

if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d /usr/etc ]; then
  conf_dir="/usr/etc"
elif [ -d /etc ]; then
  conf_dir="/etc"
fi

if [ -d $conf_dir/time ]; then
  if [ -e $conf_dir/time/data/tools.dat ]; then
    tools_data="$conf_dir/time/data/tools.dat"
  fi
  if [ -e $conf_dir/time/data/category.dat ]; then
    category_data="$conf_dir/time/data/category.dat"
  fi
else
  if [ -e data/tools.dat ]; then
    tools_data="data/tools.dat"
  fi
  if [ -e data/category.dat ]; then
    category_data="data/category.dat"
  fi
fi

if [ -e /usr/lib/sudo ]; then
  sudo="sudo"
elif [ -e /usr/bin/sudo ]; then
  sudo="sudo"
elif [ -e /lib/sudo ]; then
  sudo="sudo"
elif [ -e /bin/sudo ]; then
  sudo="sudo"
elif [ -e /data/data/com.termux/files/usr/bin/sudo ]; then
  sudo="sudo"
else
  sudo=""
fi

if [ -e /bin/apt ]; then
  pac="apt-get"
  system="linux"
elif [ -e /bin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /usr/bin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /bin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/bin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /bin/brew ]; then
  pac="brew"
  system="mac"
elif [ -e /usr/bin/brew ]; then
  pac="brew"
  system="mac"
elif [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ -e /data/data/com.termux/files/usr/bin/apt ]; then
  pac="apt"
  system="termux"
elif [ -e /data/data/com.termux/files/usr/bin/apt-get ]; then
  pac="apt-get"
  system="termux"
fi

# setup process
clear
echo "$logo"
echo "\033[01;32m Installing .... \033[00m"
sleep 1
echo "\033[01;33m Running setup .... \033[00m"
sleep 1

# installing dependency
if [ ! -e $bin/wget ]; then
  if [ $sudo ]; then
    $sudo $pac install wget -y
  else
    $pac install wget -y
  fi
fi
if [ ! -e $bin/curl ]; then
  if [ $sudo ]; then
    $sudo $pac install curl -y
  else
    $pac install curl -y
  fi
fi
if [ ! -e $bin/git ]; then
  if [ $sudo ]; then
    $sudo $pac install git -y
  else
    $pac install git -y
  fi
fi

# removing old one
if [ -e $bin/time ]; then
  if [ -d $conf_dir/time ]; then
    if [ $sudo ]; then
      $sudo rm -rf $bin/time
      $sudo rm -rf $conf_dir/time
    else
      rm -rf $bin/time
      rm -rf $conf_dir/time
    fi
  fi
fi

# install time
if [ $0 = "install" -o $0 = "./install" ]; then
  if [ -e time ]; then
    if [ $sudo ]; then
      $sudo mv -v time $bin
      $sudo chmod +x $bin/time
    else
      mv -v time $bin
      chmod +x $bin/time
    fi
  fi
  cd ..
  if [ -d time ]; then
    if [ $sudo ]; then
    $sudo mv -v time $conf_dir
    else
      mv -v time $conf_dir
    fi
  fi
else
  if [ -e time/time ]; then
    if [ $sudo ]; then
      $sudo mv -v time/time $bin
      $sudo chmod +x $bin/time
    else
      mv -v time/time $bin
      chmod +x $bin/time
    fi
  fi
  if [ -d time ]; then
    if [ $sudo ]; then
    $sudo mv -v time $conf_dir
    else
      mv -v time $conf_dir
    fi
  fi
fi

# check time is installed or not
if [ -e $bin/time ]; then
  if [ -d $conf_dir/time ]; then
    clear
    echo "$logo"
    echo " \033[00mtime \033[01;32minstalled successfully !!"
    echo " \033[01;32mtype \033[00m'time -h'\033[01;32m for more.\033[00m"
  else
    clear
    echo "$logo"
    echo " \033[01;31mSorry \033[00m: time \033[01;31mis not installed !!"
    echo " \033[01;32mPlease try again\033[00m"
  fi
fi